default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: test
  password: test
  redis:
    host: localhost
    port: 6379
    db: 0
    options:
      namespace: ci-test

development:
  <<: *default
  database: ci_development

test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: ci_test
