default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  database: ci_development
  user: root

test:
  <<: *default
  database: ci_test
  user: root

production:
  <<: *default
  database: heroku_1b46c117451d679
  user: root

